apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: elasticsearch-sysctl-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: elasticsearch-chown-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["chown", "1000:1000", "-R", "/usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      containers:
      - name: elasticsearch
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: zammad/zammad-docker-compose:zammad-elasticsearch
        imagePullPolicy: Always
        resources:
          requests:
            memory: 1024Mi
          limits:
            memory: 1024Mi
        env:
        #- name: "bootstrap.memory_lock" should be fixed in next major kubernetes release
        #  value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: "elasticsearch-data"
          emptyDir: {} # change me to persistent storage
