apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
  namespace: default
  labels:
    app: memcached
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      terminationGracePeriodSeconds: 10

      containers:
      - name: memcached
        image: zammad/zammad-docker-compose:zammad-memcached
        args: [ "zammad-memcached" ]
        ports:
        - containerPort: 11211
          name: memcached
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 10
          periodSeconds: 10
